language: python
sudo: false
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"

install:
    - pip install tox flake8

script:
    - tox -e py
    - make stylecheck

branches:
  except:
    - website

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
