作者简介
----------

我的名字叫做 Robert Picard。我是 Matasano Security 的一名安全顾问并且也是一个 Flask 爱好者。我喜欢 Flask 的简洁性，相对来说像 Django 框架给用户准备所有的东西，这种模式适用于许多的人，但是并不适用我。

如果你想要联系我，请直接发送邮件到 robert@robert.io。如果你对本书有反馈意见的话，请反馈到 `GitHub repository <https://github.com/rpicard/explore-flask>`_ 上。


入门篇
--------

如果你是一个新的 Werkzeug 或者 WSGI 开发，一般情况下你应该从这里开始。

.. toctree::
   :maxdepth: 3

   primer/index



进阶篇
-------------------

开发服务器和测试支持和管理脚本工具的内容在这里:

.. toctree::
   :maxdepth: 3

   advance/index



实战篇
---------

.. toctree::
   :maxdepth: 3

   practice/index




许可证
-------

Copyright (c) 2015-2015 [DanDeng, Inc.](http://www.pythondoc.com/) 以及其它的贡献者。

在 Apache 许可证（版本2.0）下授权（以下简称“许可证”）；除非你遵守许可证，否则你可能不能使用这个文件。你可以到这里获取一份许可证的副本：

   http://www.apache.org/licenses/LICENSE-2.0


除非因适用法律需要或书面同意，根据许可证分发的软件是基于"按原样"基础提供，无任何明示的或暗示的保证或条件。详见根据许可证许可下，特定语言的管辖权限和限制。


贡献
-------
本项目是托管在 `on GitHub <https://github.com/sixu05202004/flask-cookbook>`_ 上并且欢迎拉请求（pull requests）！